In [13]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [36]:
import numpy as np
import math

In [43]:
def minor(matrix, i, j):
    """
    Returns the minor of the element at row i and column j in the given matrix.
    """
    return determinant([row[:j] + row[j+1:] for row in (matrix[:i]+matrix[i+1:])])

def determinant(matrix):
    """
    Returns the determinant of the given matrix.
    """
    if len(matrix) == 1:
        return matrix[0][0]
    elif len(matrix) == 2:
        return matrix[0][0]*matrix[1][1] - matrix[0][1]*matrix[1][0]
    else:
        det = 0
        for j in range(len(matrix)):
            det += ((-1)**j)*matrix[0][j]*determinant([row[:j]+row[j+1:] for row in matrix[1:]])
        return det

def minors(matrix):
    """
    Returns a new matrix containing the minors of the given matrix.
    """
    return [[minor(matrix, i, j) for j in range(len(matrix[0]))] for i in range(len(matrix))]

In [44]:
def cofactor(matrix):
    """
    Returns a new matrix containing the cofactors of the given matrix.
    """
    return [[(-1)**(i+j) * matrix[i][j] for j in range(len(matrix[0]))] for i in range(len(matrix))]


In [45]:
matrix = [[2, 5, -1], [1, 4, 3], [2, -3, 5]]
minors_matrix = minors(matrix)
cofactors_matrix = cofactor(minors_matrix)

print("minors matrix")
print(*minors_matrix, sep = '\n')
print('\n')
print("cofactors matrix")
print(*cofactors_matrix, sep = '\n')
print('\n')

minors matrix
[29, -1, -11]
[22, 12, -16]
[19, 7, 3]


cofactors matrix
[29, 1, -11]
[-22, 12, 16]
[19, -7, 3]




In [49]:
def determinate():
    return np.linalg.det(matrix)

In [50]:
print("determinate")
print(round(determinate(), 1))

determinate
74.0


In [57]:
def inverse():
    return np.linalg.inv(matrix)

In [59]:
print("inverse")
print(inverse())

inverse
[[ 0.39189189 -0.2972973   0.25675676]
 [ 0.01351351  0.16216216 -0.09459459]
 [-0.14864865  0.21621622  0.04054054]]
